projectName: WellCompareDir
projectUrl: https://joelpurra.com/projects/WellCompareDir/
projectRedirectBaseUrl: https://joelpurra.com/projects/WellCompareDir
projectGithub: https://github.com/joelpurra/wellcomparedir
projectStackoverflow: https://stackoverflow.com/search?q=wellcomparedir
